### ISSUE TITLE
Can I use this mod with only alxr without alvr on latest version?

### ISSUE THREAD

**Issue by sjsanjsrh** [dfgHiatus/QuestPro4Neos#8]
Currently I can't use alvr, so i want to use only airlink and alxr. Expression works in v0.0.1, but not in 2.0.0. I would like to know which version of alxr was developed using.

**Comment by dfgHiatus** [comment]
Hey there, this should be the version: https://github.com/dfgHiatus/QuestPro4Neos/issues/5

**Comment by sjsanjsrh** [comment]
Is it impossible to use only alxr without alvr?

**Comment by dfgHiatus** [comment]
I would not know, I do not have a quest pro myself. I can only do my best to point you in the right direction, sorry
